apiVersion: v2
name: envrouter
description: Env Router Helm chart for Kubernetes
type: application
version: "0.2.0"
appVersion: "v0.2"
maintainers:
  - name: Ivan Volynkin
    email: jonasasx@gmail.com
    url: ivolynkin.ru